nick: tamer
url: https://4069.twt.social/user/tamer/twtxt.txt
following:
  71m: https://timmorgan.org/twtxt.txt
  Antonio: https://twtxt.net/user/antonio/twtxt.txt
  abliss: https://abliss.keybase.pub/twtxt.txt#7a778276dd852edc65217e759cba637a28b4426b
  akraut: https://akraut.keybase.pub/twtxt.txt
  alip: https://dev.exherbo.org/~alip/twtxt.txt
  autoalk: http://autoalk.tk/twtxt/autoalk.txt
  benaiah: https://benaiah.me/twtxt.txt
  buckket: https://buckket.org/twtxt.txt
  c-keen: http://pestilenz.org/~ckeen/twtxt.txt
  clementd: http://clementd-files.cellar.services.clever-cloud.com/twtxt.txt
  crypto: https://4069.twt.social/user/crypto/twtxt.txt
  dave: https://davebucklin.com/twtxt.txt
  deepend: https://yourtilde.com/~deepend/twtxt.txt
  edsu: http://edsu.github.io/twtxt/twtxt.txt
  eli_oat: https://txt.eli.li/twtxt/twtxt.txt
  esc: http://escowles.github.io/tw.txt
  fegffb: https://feg-ffb.de/twtxt.txt
  frogorbits.com: https://www.frogorbits.com/twtxt.txt
  fundor333: https://fundor333.com/twtxt.txt
  gbmor: https://gbmor.dev/twtxt.txt
  gil: https://tilde.pt/~gil/twtxt.txt
  hjertnes: https://hjertnes.social/twtxt.txt
  james: https://4069.twt.social/user/james/twtxt.txt
  jb55: https://jb55.com/twtxt.txt
  jcolag: https://john.colagioia.net/twtxt.txt
  johanbove: https://johanbove.info/twtxt.txt
  kas: https://enotty.dk/twtxt.txt
  kasdk: https://enotty.dk/kasdk.txt
  lahvak: http://lahvak.github.io/twtxt/twtxt.txt
  leo: https://www.gkbrk.com/twtxt.txt
  lucidiot: https://tilde.town/~lucidiot/twtxt.txt
  marado: https://tilde.pt/~marado/twtxt.txt
  mdom: https://domgoergen.com/twtxt/mdom.txt
  mdosch: https://mdosch.de/twtxt.txt
  melyanna: https://tilde.club/~melyanna/twtxt.txt
  mk: http://mk.sdf.org/twtxt.txt
  mr_woggle: https://tilde.town/~mr_woggle/twtxt.txt
  nblade: http://nblade.sdf.org/twtxt/twtxt.txt
  news: https://4069.twt.social/user/news/twtxt.txt
  pbatch: https://pbat.ch/twtxt.txt
  pelmel: http://pelmel.org/twtxt.txt
  quite: https://lublin.se/twtxt.txt
  reednj: http://twtxt.xyz/user/8c2b4bbfa328944ba.txt
  ruebot: http://ruebot.github.io/twtxt/twtxt.txt
  sdk: https://codevoid.de/tw.txt
  selin: https://4069.twt.social/user/selin/twtxt.txt
  sixbitproxywax: https://sixbitproxywax.com/twtxt.txt
  svf: http://scott.vranesh-fallin.com/twtxt.txt
  sysdharma: https://twtxt.lpho.de/twtxt.txt
  tamer: https://4069.twt.social/user/tamer/twtxt.txt
  tfurrows: https://grex.org/~tfurrows/twtxt.txt
  tildebeast: https://tilde.team/~tildebeast/twtxt/twtxt.txt
  tux0r: https://twtxt.rosaelefanten.org
  twet: https://lublin.se/twet.txt
  twtxt: https://buckket.org/twtxt_news.txt
  tx: https://shroom.party/twtxt.txt
  vinc: https://vinc.cc/twtxt.txt
  von: https://tilde.town/~von/twtxt.txt
  xandkar: https://xandkar.net/twtxt.txt
